name = "MolarWeight"
uuid = "9455ca06-40b2-46b5-a1e8-4d545d81a278"
authors = ["Selene Sofi pomc.ecc@gmail.com ans contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
