#
# Atomic database using formal values of https://en.wikipedia.org/wiki/Standard_atomic_weight#:~:text=The%20standard%20atomic%20weight%20(A,atomic%20mass%20constant%20mu.
#

atomic_weight = Dict(
    "h"  =>   1.008
    "he" =>   4.002_602
    "li" =>   6.94
    "be" =>   9.012_183_1
    "b"  =>  10.81
    "c"  =>  12.011
    "n"  =>  14.007
    "o"  =>  15.999
    "f"  =>  18.998_403_163
    "ne" =>  20.179_7
    "na" =>  22.989_769_28
    "mg" => 
    "al" => 
    "si" => 
    "p"  => 
    "s"  =>    
    "cl" =>
    "ar" =>
    "k"  =>
    "ca" =>
    "sc" =>
    "ti" =>
    "v"  =>
    "cr" =>
    "mn" =>
    "fe" =>
    "co" =>
    "ni" =>
    "cu" =>
    "zn" =>
    "ga" =>
    "ge" =>
    "as" =>
    "se" =>
    "br" =>
    "kr" =>
    "rb" =>
    "y"  =>
    "zr" =>
    "nb" =>
    "mo" =>
    "tc" =>
    "ru" =>
    "rh" =>
    "pd" =>
    "ag" =>
    "cd" =>
    "in" =>
    "sn" =>
    "sb" =>
    "te" =>
    "i"  =>
    "xe" =>
    "cs" =>
    "ba" =>
    "la" =>
    "ce" =>
    "pr" =>
    "nd" =>
    "pm" =>
    "sm" =>
    "eu" =>
    "gd" =>
    "tb" =>
    "dy" =>
    "ho" =>
    "er" =>
    "tm" =>
    "yb" =>
    "lu" =>
    "hf" =>
    "ta" =>
    "w"  =>
    "re" =>
    "os" =>
    "ir" =>
    "pt" =>
    "au" =>
    "hg" =>
    "tl" =>
    "pb" =>
    "bi" =>
    "po" =>
    "at" =>
    "rn" =>
    "fr" =>
    "ra" =>
    "ac" =>
    "th" =>
    "pa" =>
    "u"  =>
    "np" =>
    "pu" =>
    "am" =>
    "cm" =>
    "bk" =>
    "cf" =>
    "es" =>
    "fm" =>
    "md" =>
    "no" =>
    "lr" =>
    "rf" =>
    "db" =>
    "sg" =>
    "bh" =>
    "hs" =>
    "mt" =>
    "ds" =>
    "rg" =>
    "cn" =>
    "nh" =>
    "fl" =>
    "mc" =>
    "lv" =>
    "ts" =>
    "og" =>
)